version: "3.8"

services:
  emailsender-api:
    build:
      context: .
      args:
        - ENV_VALUE=Production
        - PFX_PASSWORD=${PFX_PASSWORD}
      dockerfile: dockerfile
    hostname: emailsender
    ports:
      - "80:8080"
      - "443:8081"
    volumes:
      - /opt/configs/emailsender-apis-prod.json:/app/appsettings.Production.json:ro
      - /opt/certs/wildcard-emailsender.dev.pfx:/https/wildcard-emailsender.dev.pfx:ro