// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EmailSender.Persistence.Database.Migrations
{
    public partial class ChangeColumnNameAndType : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsInvoiceSent",
                table: "Billing");

            migrationBuilder.AddColumn<DateTime>(
                name: "InvoiceSentDate",
                table: "Billing",
                type: "datetime2",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "InvoiceSentDate",
                table: "Billing");

            migrationBuilder.AddColumn<bool>(
                name: "IsInvoiceSent",
                table: "Billing",
                type: "bit",
                nullable: false,
                defaultValue: false);
        }
    }
}
