// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace EmailSenderService.Backend.Database.Migrations
{
    public partial class AddColumnsToEmailTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "ServerKey",
                table: "Email",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "ServerName",
                table: "Email",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "ServerPort",
                table: "Email",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<bool>(
                name: "ServerSsl",
                table: "Email",
                type: "bit",
                nullable: false,
                defaultValue: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ServerKey",
                table: "Email");

            migrationBuilder.DropColumn(
                name: "ServerName",
                table: "Email");

            migrationBuilder.DropColumn(
                name: "ServerPort",
                table: "Email");

            migrationBuilder.DropColumn(
                name: "ServerSsl",
                table: "Email");
        }
    }
}
