// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EmailSenderService.Backend.Database.Migrations
{
    public partial class RenameTableName : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RegisteredEmail");

            migrationBuilder.CreateTable(
                name: "AllowEmail",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    UserId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    EmailId = table.Column<Guid>(type: "uniqueidentifier", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AllowEmail", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AllowEmail_Email",
                        column: x => x.EmailId,
                        principalTable: "Email",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_AllowEmail_User",
                        column: x => x.UserId,
                        principalTable: "User",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AllowEmail_EmailId",
                table: "AllowEmail",
                column: "EmailId");

            migrationBuilder.CreateIndex(
                name: "IX_AllowEmail_UserId",
                table: "AllowEmail",
                column: "UserId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AllowEmail");

            migrationBuilder.CreateTable(
                name: "RegisteredEmail",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    EmailId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    UserId = table.Column<Guid>(type: "uniqueidentifier", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RegisteredEmail", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RegisteredEmail_Email",
                        column: x => x.EmailId,
                        principalTable: "Email",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_RegisteredEmail_User",
                        column: x => x.UserId,
                        principalTable: "User",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_RegisteredEmail_EmailId",
                table: "RegisteredEmail",
                column: "EmailId");

            migrationBuilder.CreateIndex(
                name: "IX_RegisteredEmail_UserId",
                table: "RegisteredEmail",
                column: "UserId");
        }
    }
}
